### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by talhairfanbentley** [eclipsesource/J2V8#456] opened 2019-02-26 10:02 UTC
**Step:**  
           `nodejs diff apply`
**Error:**
`[apply-diff]
Applying Node.js patch: node.patches\7.4.0.diff
error: patch failed: common.gypi:183
error: common.gypi: patch does not apply
error: patch failed: deps/cares/common.gypi:80
error: deps/cares/common.gypi: patch does not apply
error: patch failed: deps/uv/common.gypi:87
error: deps/uv/common.gypi: patch does not apply
error: patch failed: src/node.h:414
error: src/node.h: patch does not apply
Traceback (most recent call last):
  File "./nodejs.py", line 332, in <module>
    cmd_handler.function(sys.argv[3:])
  File "./nodejs.py", line 272, in apply_diff
    utils.execute("git apply " + os.path.join("..", patch_file), "node")
  File "C:\Users\Talha.Irfan\OneDrive - Bentley Systems, Inc\Desktop\app\J2V8\build_system\build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'git apply ..\node.patches\7.4.0.diff' returned non-zero exit status 1`

**Comment by irbull** [comment] 2019-04-26 21:22
Closing as a duplicate of #458 and #459.

**Closed by irbull** 2019-04-26 21:22 UTC

**Comment by Twometer** [comment] 2019-06-03 10:02
How is that a duplicate?
