### ISSUE TITLE
J2V8 native library not loaded - only on SDK 23

### ISSUE THREAD

**Issue by parahall** [eclipsesource/J2V8#174] opened 2016-06-22 14:19 UTC
Target SDK: 23
Device: Nexus 6P, Nexus 5X with Marshmallow

java.lang.IllegalStateException:J2V8 native library not loaded.
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[,nativeLibraryDirectories=[/data/app/com.gettaxi.dbx.android-1/lib/arm64, /data/app/com.gettaxi.dbx.android-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64] couldn't find "libj2v8.so"

Shared libraries that have text relocations are now rejected. This is documented here: https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime

You'll have to fix them, which means you need to have access to the native code and NDK prepared. Easiest workaround is to add -fpic or -fPIC to your LOCALC_FLAGS in your Android.mk file, and then rebuild the libraries.

**Comment by parahall** [comment] 2016-06-26 08:09
@irbull need your attention :) We kind of stuck because of it

**Comment by magmastonealex** [comment] 2016-06-27 14:28
I've written a [guide](https://gist.github.com/magmastonealex/a9158173828932def9ffb81672d6c578) to how I got J2V8 and V8 compiled. It's a little involved, and requires a Linux machine, but it does offer a temporary fix until the official builds are updated.

Your suggested to add `-fPIC` to `LOCALC_FLAGS` worked perfectly, once I managed to get V8 to build.

You also *may* be able to shortcut building V8 and the `ndk-build` step by copying the libs folder from the latest official AAR release into the J2V8 source folder, but I haven't tested this at all.

**Comment by irbull** [comment] 2016-06-28 03:19
@parahall can you take a look at fb30aadff38a59f95348e3fdd00c955265c6b08a and tell me if you think it will do the trick. I'll get a build out.

**Comment by irbull** [comment] 2016-06-28 13:11
This is included in 4.2.0-SNAPSHOT. If someone can test and let me know, I plan on releasing a 4.2 final this week.

**Comment by parahall** [comment] 2016-06-28 14:07
@irbull from which repository to take a snapshot?

**Comment by irbull** [comment] 2016-06-29 00:53
```
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
```
`compile 'com.eclipsesource.j2v8:j2v8:4.2.0-SNAPSHOT@aar'`

**Comment by parahall** [comment] 2016-06-29 05:51
@irbull Hi, 
I tried with 4.2.0-SNAPSHOT, but unfortunately, it doesn't work.
Still same error: 
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader
nativeLibraryDirectories=[/data/app/com.gettaxi.dbx.android-1/lib/arm64, /data/app/com.gettaxi.dbx.android-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libj2v8.so"

Nexus 6P, Marshmallow...

**Comment by magmastonealex** [comment] 2016-06-29 20:40
From some research and reading, this appears to be unrelated to text relocations being forbidden now. My build which was compiled with `-fPIC` produces the same error (now, didn't before, I'm not sure what's changed, I'm looking).

Text relocation issues instead produce "java.lang.UnsatisfiedLinkError: dlopen failed", instead of "couldn't find libj2v8.so", based on other Github issues and SO posts.

The only thing that seems to be common is that this is happening on 64 bit devices, and the exception would seem to point to it not searching in 32 bit library directories at all. 

My fix so far has been to back compileSdkVersion and buildToolsVersion down to level 22. That stops the exception, and with my build (and 4.2.0-SNAPSHOT) also no longer produces a warning about relocations in the console.

I think rather something has changed in the level 23 SDK which changes the search path for libraries on 64 bit devices.

**Comment by irbull** [comment] 2016-06-30 02:16
From what I've read, when using a 64bit processor, Android will try to load the 32 bit binaries if all binaries are available in 32 bit form (that is, you cannot mix and match 64 and 32 bit). Maybe this changed recently. It might be a good idea to look at compiling the native bits of J2V8 in arm64 now. This requires building V8 in Arm64 something that wasn't possible when I started J2V8 2 years ago, but this has likely changed. 

I'm going on vacation for 2 weeks. I can look at that when I return. For now, I would try sticking with SDK 22 when building.

**Comment by parahall** [comment] 2016-06-30 07:43
@irbull have a nice vacation. 
Unfortunately for us, it's not an option... we cannot downgrade our support to SDK 22.
Can be the fix to compile .so for 64bit architecture separately and rely on fallback to 32 bit binaries?

**Comment by parahall** [comment] 2016-06-30 08:10
Ok. @irbull @magmastonealex 
I found the workaround.
When you install an APK on Android, the system will look for native libraries directories (armeabi, armeabi-v7a, arm64-v8a, x86, x86_64, mips64, mips) inside the lib folder of the APK, in the order determined by Build.SUPPORTED_ABIS.

If your app happen to have an arm64-v8a directory with missing libs, the missing libs will not be installed from another directory, the libs aren't mixed. That means you have to provide the full set of your libraries for each architecture.

So, to solve your issue, you can remove your 64-bit libs from your build, or set abiFilters to package only 32-bit architectures:

```
android {
    ....
    defaultConfig {
        ....
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
    }
}
```

However it's just a workaround and there is no way around to have 64bit lib version in j2v8 build.

**Comment by parahall** [comment] 2016-07-28 20:20
@irbull can we close it? :) did you managed to add 64bit to build?

**Comment by 4brunu** [comment] 2016-11-08 13:24
I'm facing the same issue.
Any news on this?
Thanks

**Comment by eckoj433** [comment] 2016-11-17 13:15
same issue, any updates on this?

**Comment by Delphian2015** [comment] 2016-12-14 12:24
I added to Gradle
    compile 'com.eclipsesource.j2v8:j2v8_android_x86:3.0.1'
    compile 'com.eclipsesource.j2v8:j2v8_android:3.0.5'

Then started example on SDK23 and SDK22 (x86_64) and have the same problem: java.lang.IllegalStateException: J2V8 native library not loaded.

then I added
ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }

but it can't help
May be somebody to solve the problem?

**Comment by whkailee** [comment] 2017-01-12 03:25
@parahall 's work around does work, but will it be a proper solution some time?

**Comment by Nims72** [comment] 2017-03-10 04:33
Also waiting for a proper fix for this.

**Comment by mrmaffen** [comment] 2017-03-21 18:11
Same problem here. I'd rather not drop my entire arm64 build just for the sake of having j2v8 work. Can you add an arm64 .so to the build on maven central? Thanks for your hard work!

**Comment by mrmaffen** [comment] 2017-03-21 18:38
@irbull Seems v8 can now be build for arm64 https://github.com/v8/v8/wiki/Cross-compiling-for-ARM

**Comment by amrish7** [comment] 2017-08-23 19:37
Any updates on this? Waiting for a proper fix

**Comment by matiwinnetou** [comment] 2017-08-23 19:57
@amrish7 better than waiting for a proper fix, one can try to contribute...

**Comment by amrish7** [comment] 2017-08-23 20:03
@matiwinnetou Well, I think everyone gets that part! Just wanted to check if it is work in progress before investing my time on fixing it 😃

**Comment by objectorange** [comment] 2017-09-19 22:18
Any updates on this? Having same issue.

**Comment by objectorange** [comment] 2017-09-20 02:07
Found the solution! Need to pull in the right library for SDK25: compile 'com.eclipsesource.j2v8:j2v8:4.5.0@aar'

**Comment by eranbet** [comment] 2017-10-17 10:51
@objectorange, did 4.5.0 solve the missing 64bit binary for you? I tried both 4.5.0 and 4.8.0 but the issue wasn't solved.
@parahall workaround did it for me but this makes me drop support for 64bit, which I don't want to undergo.
Will try using @magmastonealex solution though I guess a "formal" release/build is preferable.

**Comment by whkailee** [comment] 2017-10-19 04:21
I only use
compile 'com.eclipsesource.j2v8:j2v8_android:3.0.5'
and it works on Nexus 6P sdk 23-25 64bit 
Anyone has got idea why it works?

**Comment by eranbet** [comment] 2017-10-19 07:19
@whkailee Do you have any additional 64bit native libs in your APK? As long as you don't, everything should be fine.

**Comment by DenBond7** [comment] 2017-10-31 10:08
Received such error. 
```
java.lang.IllegalStateException: J2V8 native library not loaded
        at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:253)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:153)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:114)
        at com.example.Js.<init>(Js.java:62)
```

Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.debug-2/lib/arm64, /data/app/com.example.debug-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libj2v8.so".


That error happens when I use Android Studio 3.0 --> Run --> Edit Configurations --> Tab "Profiling" "enable advanced profiling" - enabled

![image](https://user-images.githubusercontent.com/2863246/32218167-c87a1e24-be32-11e7-8096-cbf7cd4283f6.png)

```
BUILD_TOOLS_VERSION=27.0.0
COMPILE_SDK_VERSION=26
TARGET_SDK_VERSION=26
MIN_SDK_VERSION=19
ANDROID_GRADLE_VERSION=3.0.0

implementation 'com.eclipsesource.j2v8:j2v8:4.8.0@aar'
```

In the folder `"/data/app/com.example.debug-2/lib/arm64"` I have only libsupportjni.so.

**Comment by oakpip** [comment] 2017-11-14 09:01
how to fix this issues, how ????

**Comment by FrancisShi** [comment] 2018-03-06 12:36
remove arm64-v8a
works

**Comment by roman01la** [comment] 2018-12-18 16:41
Having this issue with local build on macOS in Linux Docker, but everything is fine when using `com.eclipsesource.j2v8:j2v8:4.8.0@aar`. Any clues why local build produces aar with text relocations?

**Comment by irbull** [comment] 2019-01-11 03:39
We now have 64 bit builds for arm and x86. See #384. 

@roman01la The text relocation was because OpenSSL was being linked in. Setting `--openssl-no-asm` fixed that. https://github.com/eclipsesource/J2V8/blob/master/build_system/config_android.py#L46

**Closed by irbull** 2019-01-11 03:39 UTC
