### ISSUE TITLE
V8 Load Error When Tomcat Restart!

### ISSUE THREAD

**Issue by niss2000** [eclipsesource/J2V8#177] opened 2016-06-27 02:34 UTC
Version: 3.1.6
Env: Eclipse+Tomcat7
Other: SpringMVC
j2v8 released(using code) when tomcat restart,but error was caught also,I found that the lib file cannot be deleted:
LibraryLoader.java(line:104):
//can't delete file
if (file.exists()) {
 file.delete();
}
so, when it extrat and write file,error occurs:
LibraryLoader.java(line:113):
while ((read = is.read(buffer)) != -1) {
   os.write(buffer, 0, read);
}

**Comment by bergi9** [comment] 2016-07-04 12:59
same to #145

**Comment by irbull** [comment] 2019-01-11 05:05
Closing as duplicate of #145

**Closed by irbull** 2019-01-11 05:05 UTC
