### ISSUE TITLE
Could not load J2V8 library

### ISSUE THREAD

**Issue by danvinokour** [eclipsesource/J2V8#171] opened 2016-06-15 14:35 UTC
Hi,
This happened on the following devices:
HTC6535LVW
SM-N910F
LG-D690
LG-H815
HUAWEI Y511-U30

Hope the solution will not need new .so libs and will not inflate the library :/

**Comment by danvinokour** [comment] 2016-06-23 06:25
there is also a problem with nexus 6p and nexus 5x, might be a marshmallow related problem?

**Comment by w4-kang** [comment] 2016-06-24 09:56
Have you compile 'com.eclipsesource.j2v8:j2v8:4.1.0@aar' in your gradle - dependencies?

**Comment by danvinokour** [comment] 2016-06-24 10:13
No,  3.1.6.
Will 4.1.0 fix it?

**Comment by w4-kang** [comment] 2016-06-24 10:17
No, postfix @aar worked in my case.

**Comment by magmastonealex** [comment] 2016-06-24 17:54
This is the same issue described in #174, I think. Adding `@aar` won't fix it.  The problem is that the final .so isn't compiled with `-fPIC`. 

You'll need to build from source if you want to fix it, as described in #174. My temporary fix until I have time to figure that out was to bump the `buildSdkVersion` down to 22.

**Comment by irbull** [comment] 2019-01-11 05:04
If you are also using 64-bit libraries in your application, then J2V8 will fail to load. We are now able to build 64-bit J2V8 binaries (see #384).

**Closed by irbull** 2019-01-11 05:04 UTC
