### ISSUE TITLE
Object released underneath me?

### ISSUE THREAD

**Issue by djMax** [eclipsesource/J2V8#54] opened 2015-05-20 03:39 UTC
I have some JS that calls back into Java code passing a V8Object which is saved as a member variable in the Java side. When I go to use that object in a subsequent method call, it has been released. Why? I'm hoping I don't have to retain the objects manually?

**Comment by irbull** [comment] 2015-05-20 04:45
Objects that you create, you must release. Objects that the system creates, it will release. This is true for everything except objects that are passed back down the stack (i.e. return results) where the logic must be flipped.

In the case of callback parameters, the system created the object so it will release it. However, there is a twin() method that will create a new Java object pointing at the same V8 Object. It has it's own resources, but point to the same V8 Object, so it's really the same thing. This was pushed to the SNAPSHOT repo about an hour ago. 

closed as a duplicate of issue #49.

**Closed by irbull** 2015-05-20 04:45 UTC
