### ISSUE TITLE
please add libj2v8.so on arm64-v8a  mips64 x86_64  abis

### ISSUE THREAD

**Issue by tangzhengqian** [eclipsesource/J2V8#370] opened 2017-12-12 09:18 UTC
please add libj2v8.so on arm64-v8a  mips64 x86_64  abis

**Comment by liao123abc** [comment] 2017-12-15 02:13
Day by day, I login github and check up J2V8 when I wake up, cause I really need its support for arm64-v8a mips64 x86_64 abis on Android.
But, it fails me!
It hurts my feelings.

**Comment by liao123abc** [comment] 2017-12-15 02:14
Day by day, I login github and check up J2V8 when I wake up, cause I really need its support for arm64-v8a mips64 x86_64 abis on Android.
But...
It hurts my feelings.

**Comment by irbull** [comment] 2019-01-11 04:05
Closed as a duplicate of #384

**Closed by irbull** 2019-01-11 04:05 UTC
