### ISSUE TITLE
J2V8 - node.js update

### ISSUE THREAD

**Issue by BuffaloBorn** [eclipsesource/J2V8#407] opened 2018-07-27 17:30 UTC
I'm currently using j2v8 4.6.0 but the nodejs that is included is 4.6.85.1. Is there away for me to update the latest version of nodejs by replacing the libj2v8_linux_x86_64.so file?

I have limited access to the source code and will like to only update libj2v8_linux_x86_64.so.

**Comment by gosp** [comment] 2018-08-17 03:35
@BuffaloBorn the official release for linux is v4.8.0
You can download it:
http://central.maven.org/maven2/com/eclipsesource/j2v8/j2v8_linux_x86_64/4.8.0/

**Comment by gosp** [comment] 2018-08-17 03:38
@matiwinnetou 
By the way, your [personal build](https://keybase.pub/matiwinnetou/J2V8/) for linux which support nodejs v8.2.1 can't run in ubuntu.
```
Exception in thread "nodejs-worker" java.lang.UnsupportedOperationException: StartNodeJS Not Supported.
	at com.eclipsesource.v8.V8._startNodeJS(Native Method)
	at com.eclipsesource.v8.V8.createNodeRuntime(V8.java:1013)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:101)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:48)
```

**Comment by matiwinnetou** [comment] 2018-08-17 07:06
I compiled a couple of versions here, snapshot from master at that time:

https://keybase.pub/matiwinnetou/J2V8

**Comment by rajeshpandry** [comment] 2018-11-04 05:05
@ matiwinnetou . Is it possible to get node Version of v8.11.2  for windows 64 bit version? 
Or instruct me how to compile the version on latest V8 VM.

**Comment by irbull** [comment] 2019-01-11 04:43
I'm closing this as a duplicate of #334. There is lots of information there about updating to a newer version of V8.

**Closed by irbull** 2019-01-11 04:43 UTC
