### ISSUE TITLE
Add support for the latest version of Node.js (8.12.0 or 11.0.0)

### ISSUE THREAD

**Issue by Luluno01** [eclipsesource/J2V8#429] opened 2018-10-27 14:58 UTC
I'm trying to build J2V8 with the latest Node.js as there is no official build with Node.js 8.x or above for Windows (x86-64). The followings are my building steps with some custom changes:

1. Set Node.js version to `11.0.0` in `build_system/build_settings.py`
2. Run `nodejs git clone`
3. Modify the source code of Node.js manually and generate a diff file `node.patches/11.0.0.diff`
4. Run `build -i`, select configuration 9 and enter `nodejs` to build Node.js (succeeded)
5. Modify `njs_libs` in `cmake/NodeJsUtils.cmake`
6. Run `build -i`, select configuration 9 and enter `j2v8` (failed when linking)

The errors consist of `already defined` and `unresolved external symbol _register_xxx`. Sadly I have no I idea how to make the `njs_libs` list right :(.

Here is a [repo](https://github.com/Luluno01/J2V8/) that contains the changes I've made (last two commits).

**Comment by irbull** [comment] 2019-01-11 04:18
Closing as a duplicate of #334.

**Comment by irbull** [comment] 2019-01-11 04:19
There is lots of information there. But in order to help move the project forward, I need to get a handle on the open issues. Thanks for reporting this, and letting me know that this is important!

**Closed by irbull** 2019-01-11 04:18 UTC

**Comment by Luluno01** [comment] 2019-01-11 05:13
@irbull Thank you for your reply. If you are taking these two issues as duplicated, then you mean they are all about "update the core dependency of J2V8", right? I would like to be involved in such an interesting task, however, I have no sufficient related knowledge XD. Anyway, I am looking forward to the new version of J2V8 with the lasted Node.js runtime.
