### ISSUE TITLE
Can't get object declared with "let", "const".

### ISSUE THREAD

**Issue by w4-kang** [eclipsesource/J2V8#175] opened 2016-06-23 13:53 UTC
Enviroment : Android (compileSdkVersion 23, min 19, target 21)
Version : com.eclipsesource.j2v8:j2v8:4.1.0@aar

Hi. I'm trying to get javascript object in Android platform.

I could get object from my script. Like below

succeed javascript : 

```
var someObject = {
  someFunction: function functionName() {
    const resultObject = {
      aProperty: 'value',
    };
    return resultObject; 
  },
};
```

java : 

```
V8Object javaObject  = runtime.getObject("someObject");
javaObject.executeObjectFunction("functionName");
```

But, I fail to get object with blow script.
I couldn't load javascript object declared with "let" and "const".

failed javascript :

```
let someObject = {
  someFunction: function functionName() {
    const resultObject = {
      aProperty: 'value',
    };
    return resultObject; 
  },
};
```

```
const someObject = {
  someFunction: function functionName() {
    const resultObject = {
      aProperty: 'value',
    };
    return resultObject; 
  },
};
```

Even though variable in function is declared with let or const, function works well in java.
But when target javascript object of runtime.getObject() is declared with const or let, getObject returns V8Object with undefined.

I'd like to know why it happened in detail.
Should I declare all functions and variable with "var" ?
or only target of runtime.getObject()?

**Comment by irbull** [comment] 2016-06-24 18:24
Thank-you for this. I can reproduce this even with the most recent builds of V8 and J2V8. J2V8 didn't originally target ES6, but I think this is important. Here is a testcase that demonstrates the problem:
```
    @Test
    public void testGetFromLet() {
        System.out.println(V8.getV8Version());
        v8.executeVoidScript("let foo = [1,2,3]");

        V8Array array = v8.getArray("foo");

        assertEquals(3, array.length());
        assertEquals(1, array.getInteger(0));
        assertEquals(2, array.getInteger(1));
        assertEquals(3, array.getInteger(2));
        array.release();
    }
```

**Comment by irbull** [comment] 2017-04-04 03:03
I can't figure out how to access block scoped variables from V8. I have asked this question on the V8 users forum [1].

[1] https://groups.google.com/forum/#!topic/v8-users/QjMuu7NLDg8

**Comment by irbull** [comment] 2017-04-04 13:56
According to the the users forum, this isn't possible. This makes sense because `let` is a _blocked scoped_ variable, which means that the variable is only available when that block is in scope, and when we are back in Java, we are out of the JS scope. 

I'm (sadly) closing this because we cannot support it.

**Closed by irbull** 2017-04-04 13:56 UTC
