### ISSUE TITLE
con't run on arm64-v8a mobile?

### ISSUE THREAD

**Issue by BlueSky-YJS** [eclipsesource/J2V8#379] opened 2018-01-16 03:12 UTC
why i con't find a libs for arm64-v8a mobile?it is't can run on this device?how can I build it for this device?
and the build step is work ok?I did it as this instructions but failed...so how can I do it?

**Comment by leibniz55** [comment] 2018-11-19 05:34
because, j2v8 is not support arm64-v8a.
so, if device architecture is arm64, device don't load j2v8.

but, I solved the issue by new building a v8.

my repository is
https://github.com/leibniz55/J2V8ForArm64

I built v8 by arm, arm64, x86 for android. and then, I built j2v8 by arr. However, there is still a lack of testing.

First, I succeed load on the arm64 device. without .gradle setting

**Comment by irbull** [comment] 2019-01-10 23:46
Duplicate of #384

**Closed by irbull** 2019-01-10 23:46 UTC
