### ISSUE TITLE
emoji

### ISSUE THREAD

**Issue by fifiand1** [eclipsesource/J2V8#172] opened 2016-06-22 02:50 UTC
function.call(v8, array);
contains a emoji string

06-22 10:47:19.200 26158-26158/com.example.tinytest W/dalvikvm: JNI WARNING: NewStringUTF input is not valid Modified UTF-8: illegal start byte 0xf0
06-22 10:47:19.200 26158-26158/com.example.tinytest W/dalvikvm:              string: '<text  class="a" id="richtext">👄</text>'
06-22 10:47:19.200 26158-26158/com.example.tinytest W/dalvikvm:              in Lcom/eclipsesource/v8/V8;._arrayGetString:(JII)Ljava/lang/String; (NewStringUTF)
06-22 10:47:19.200 26158-26158/com.example.tinytest I/dalvikvm: "main" prio=5 tid=1 NATIVE
06-22 10:47:19.200 26158-26158/com.example.tinytest I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x41de1d68 self=0x41dd0700
06-22 10:47:19.200 26158-26158/com.example.tinytest I/dalvikvm:   | sysTid=26158 nice=-1 sched=0/0 cgrp=apps handle=1074663764
06-22 10:47:19.200 26158-26158/com.example.tinytest I/dalvikvm:   | state=R schedstat=( 4261044872 1530492896 15356 ) utm=360 stm=66 core=0
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #00  pc 0000132e  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #01  pc 00060976  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+33)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #02  pc 00054960  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #03  pc 000549ce  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #04  pc 00038a84  /system/lib/libdvm.so
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #05  pc 00039ebc  /system/lib/libdvm.so
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #06  pc 0003c28e  /system/lib/libdvm.so
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #07  pc 001bee86  /data/app-lib/com.example.tinytest-2/libj2v8_android_armv7l.so (Java_com_eclipsesource_v8_V8__1arrayGetString+257)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #08  pc 0001de4c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #09  pc 0004e3b2  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+397)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #10  pc 00027260  /system/lib/libdvm.so
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #11  pc 0002e220  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #12  pc 0002b8b8  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #13  pc 000608a4  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+335)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #14  pc 0004c990  /system/lib/libdvm.so
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #15  pc 0003fe86  /system/lib/libdvm.so
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #16  pc 001ba5b0  /data/app-lib/com.example.tinytest-2/libj2v8_android_armv7l.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+19)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #17  pc 001c15f2  /data/app-lib/com.example.tinytest-2/libj2v8_android_armv7l.so (voidCallback(v8::FunctionCallbackInfo<v8::Value> const&)+121)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #18  pc 0045caf0  /data/app-lib/com.example.tinytest-2/libj2v8_android_armv7l.so (v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))+152)
06-22 10:47:19.240 26158-26158/com.example.tinytest I/dalvikvm:   #19  pc 001ed25c  /data/app-lib/com.example.tinytest-2/libj2v8_android_armv7l.so

**Comment by irbull** [comment] 2016-06-22 20:01
The following test case passes. 
```
    @Test
    public void testCallFunctionWithEmojiParamter() {
        V8Function v8Function = new V8Function(v8, new JavaCallback() {

            @Override
            public Object invoke(final V8Object receiver, final V8Array parameters) {
                return parameters.get(0);
            }
        });

        V8Array paramters = new V8Array().push("👄");
        Object result = v8Function.call(null, paramters);

        assertEquals("👄", result);
        paramters.release();
        v8Function.release();
    }
```
This is likely a duplicate of #142 which was fixed in 044f46589a31794efc2cc8ccc66d9fbea9211355. Please re-open if you think this is still an issue in the latest code base (you can try this with 4.2.0-SNAPSHOT).

**Closed by irbull** 2016-06-22 20:01 UTC
