### ISSUE TITLE
JVM native crash due to Node process out of memory

### ISSUE THREAD

**Issue by midzelis** [eclipsesource/J2V8#202] opened 2016-10-02 15:12 UTC
When the Node process runs out of memory, the JVM crashes. 

Attached test case. 

This link might help with how to actually handle fatal errors in V8. 

https://stackoverflow.com/questions/16797423/how-to-handle-v8-engine-crash-when-process-runs-out-of-memory

`

import java.io.File;
import java.nio.file.Files;

import com.eclipsesource.v8.NodeJS;

public class Main {

```
public static void main(String[] args) throws Exception {
    NodeJS node = NodeJS.createNodeJS();
    File f = File.createTempFile("crash", "js");

    String script = "a = []; for (;;) { a.push(\"hello\"); }";
    Files.write(f.toPath(), script.getBytes());
    node.exec(f);
    node.handleMessage();
}
```

}
`

**Comment by midzelis** [comment] 2016-11-21 16:57
@irbull Any update on this issue? Can I help? Having the JVM crash without warning is very bad for a desktop application, especially if that app happens to be Eclipse. Could we trap the seg-fault and disable NodeJS instead of crashing the JVM?

**Comment by irbull** [comment] 2019-01-11 20:41
I'm going to mark this as a duplicate of #428. That one is really about adding some constraints or mechanism to properly handle OOM errors from V8.

**Closed by irbull** 2019-01-11 20:41 UTC
