### ISSUE TITLE
v8 memory release

### ISSUE THREAD

**Issue by omanhom** [eclipsesource/J2V8#110] opened 2015-11-26 09:57 UTC
Using the 3.0.2 linux version of my project. In the stress test, call runtime.release () method, the V8 class in the "Map functions " property definition is not clear, it is easy to cause the java process OOM.
Now I added a clear () method in the V8 class, as follows:

public void clear() {
        if (functions != null) {
            functions.clear();
        }
}

In call runtime.release (), also call clear () , but unfortunately, the program running for some time, the Linux process takes up a lot of memory, until the machine is hung up, using the top Linux command to see the following information:

![os](https://cloud.githubusercontent.com/assets/13151762/11420104/c5f7394a-9466-11e5-8ee1-369073b1afd2.png)

At the same time using jvisualvm monitoring results

![jvm](https://cloud.githubusercontent.com/assets/13151762/11420129/02357552-9467-11e5-9f3f-cae59841cef6.png)
![cpu](https://cloud.githubusercontent.com/assets/13151762/11420137/0bde5f60-9467-11e5-8c39-4f57222d63c9.png)

**Comment by irbull** [comment] 2015-11-27 05:24
Thank-you for this. I will look into stress testing with the V8 runtime.

**Comment by irbull** [comment] 2015-12-04 20:14
What else are you doing in your stress test? Are you just creating / releasing runtimes, or are you registered a number of callbacks? Can you post a short stress test unit tests that shows this behaviour?

**Comment by irbull** [comment] 2015-12-04 20:39
I can produce a leak with the following: 
```
    @Test
    public void testStressTestV8Instances() {
        for (int i = 0; i < 100000; i++) {
            System.out.println("Creating runtime: " + i);
            V8 runtime = V8.createV8Runtime();
            for (int j = 0; j < 10000; j++) {
                runtime.registerJavaMethod(new JavaCallback() {

                    @Override
                    public Object invoke(final V8Object receiver, final V8Array parameters) {
                        // TODO Auto-generated method stub
                        return null;
                    }
                }, "foo" + j);
            }
            runtime.release();
        }
    }
```

This is a duplicate of #19. I'll close that bug since this one contains more information now.

**Comment by irbull** [comment] 2015-12-04 20:46
Tracking all the MethodDescriptors and releasing them when we release the runtime fixes this issue.

**Comment by irbull** [comment] 2015-12-04 20:50
Fixed in b07a7c3e5827864c52a63d475cdc5e1a049b0253

**Closed by irbull** 2015-12-04 20:50 UTC
Labels: in progress

**Comment by omanhom** [comment] 2015-12-05 12:08
use the following:

	public class TestObject {
		public int random() {
			return new Random().nextInt(10);
		}
	}
	
	@Test
	public void testStressTestV8Instances() {
		Random random = new Random();
		String script = "test.random()+level";
		int counter1 = 1000000;
		int counter2 = 10000;
		for (int i = 0; i < counter1; i++) {
			V8 runtime = V8.createV8Runtime();
			TestObject testObject = new TestObject();
			for (int j = 0; j < counter2; j++) {
				runtime.add("level", random.nextInt(100));
				V8Object randomObj = null;
				try {
					randomObj = new V8Object(runtime);
					runtime.add("test", randomObj);
					randomObj.registerJavaMethod(testObject, "random", "random", null);
				} finally {
					if (randomObj != null)
						randomObj.release();
				}
				System.out.println(runtime.executeDoubleScript(script));
			}
			runtime.release();
		}
	}


can you release a fix 3.0.2 version to me?
include libj2v8_linux_x86_64.so and libj2v8_win32_x86_64.dll,thanks

**Comment by irbull** [comment] 2015-12-07 04:14
I've used your test case and I can reproduce the problem. With b07a7c3e5827864c52a63d475cdc5e1a049b0253 applied, it appears to be fixed. The memory sits around 70M (goes up and down a bit as the test runs).

Unfortunately I don't have the resources to backport this to 3.0.2. However, I will be releasing a 3.1.0 release this week with a few other fixes too.

Thanks for your help tracking this down.

**Comment by omanhom** [comment] 2015-12-07 05:17
great,thank you.
