### ISSUE TITLE
Fatal crash when creating isolate

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#100] opened 2015-10-29 10:46 UTC
We had a "random" crash that we weren't able to reproduce. Since it isn't totally clear what caused the problem, i can't give any further details but at least i wouldn't expect the library to crash.

Experienced on Android device with j2v8 3.0.6.

```
F/libc    (23408): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 23408 (e.tabris.js.dev)
I/DEBUG   (  181): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  181): Build fingerprint: 'google/razor/flo:5.1.1/LMY48T/2237560:user/release-keys'
I/DEBUG   (  181): Revision: '0'
I/DEBUG   (  181): ABI: 'arm'
I/DEBUG   (  181): pid: 23408, tid: 23408, name: e.tabris.js.dev  >>> com.eclipsesource.tabris.js.dev <<<
I/DEBUG   (  181): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
I/DEBUG   (  181):     r0 9fcf4268  r1 b6f85e30  r2 a1a97af8  r3 00000000
I/DEBUG   (  181):     r4 9bade000  r5 9bade000  r6 9fcf4268  r7 bea54d6c
I/DEBUG   (  181):     r8 bea54d7c  r9 00000000  sl 9fc8d338  fp bea54dbc
I/DEBUG   (  181):     ip 9f8eeeec  sp bea54d30  lr 9f66b190  pc 9f66b208  cpsr 600f0010
I/DEBUG   (  181): 
I/DEBUG   (  181): backtrace:
I/DEBUG   (  181):     #00 pc 002d9208  /data/app/com.eclipsesource.tabris.js.dev-1/lib/arm/libj2v8.so (v8::internal::Isolate::Enter()+144)
I/DEBUG   (  181):     #01 pc 001bcf39  /data/app/com.eclipsesource.tabris.js.dev-1/lib/arm/libj2v8.so (Java_com_eclipsesource_v8_V8__1createIsolate+96)
```

**Comment by irbull** [comment] 2015-10-29 14:53
I've not seen this before. Can you give some details about the exact phone and Android version that was being used?

**Comment by mpost** [comment] 2015-10-29 15:15
It was a Nexus 7 (2013) running Android 5.1.1.

**Comment by irbull** [comment] 2015-12-08 21:37
The backtrace indicates that it happened in V8 (Isolate::Enter). Since we've only seen this once, I'm going to close this as *cant_reproduce*. If we see this again, please re-open.

**Closed by irbull** 2015-12-08 21:37 UTC
Labels: bug

**Comment by matiwinnetou** [comment] 2017-07-17 18:28
Similar to: #306
