### ISSUE TITLE
What detailed article can guide me to compile success? linux / windows?

### ISSUE THREAD

**Issue by s332401890** [eclipsesource/J2V8#138] opened 2016-03-07 02:04 UTC
What detailed article can guide me to compile success? linux / windows?

**Comment by irbull** [comment] 2016-05-10 23:11
Closing as a duplicate of #151 (lots more information there). I have put build instructions for Mac and Linux in the readme. I don't have build instructions for Windows yet.

**Closed by irbull** 2016-05-10 23:11 UTC
