### ISSUE TITLE
j2v8_linux_x86_64 to snapshots?

### ISSUE THREAD

**Issue by djMax** [eclipsesource/J2V8#61] opened 2015-05-23 03:50 UTC
Any chance we can get this flavor built to snapshots? Just finished setting up CI only to realize the tests can't run because this flavor doesn't exist.

**Comment by djMax** [comment] 2015-05-23 14:58
(alternatively, some build instructions... If you give me build instructions I'll try and make a TravisCI job :) )

**Comment by irbull** [comment] 2015-05-25 20:12
Closed as a duplicate of issue #34

**Closed by irbull** 2015-05-25 20:12 UTC
