### ISSUE TITLE
How to build J2V8 for android ? (Documentation Improvement)

### ISSUE THREAD

**Issue by SKrPl** [eclipsesource/J2V8#281] opened 2017-06-15 15:13 UTC
As per the current README.md, it asks to execute the following two commands and says "*Building J2V8 for Android requires Docker*":
```
./docker/build.sh
./gradlew assembleRelease
```
But, there is no `build.sh` present in `docker` directory and the use of Docker is also not clear. It would be of great help to new users and developers if the documentation could be improved along with the addition on *"How NodeJS can be added to Android build?"* :smiley: .

**Comment by aschrijver** [comment] 2017-08-05 09:22
Yes, the build instructions are not clear to me as well. And I also want to add node on android.

**Comment by irbull** [comment] 2019-01-11 00:46
We have a new build platform and I'll be updating the docs for that. I'm going to mark this as a duplicate of #40.

**Closed by irbull** 2019-01-11 00:46 UTC
