### ISSUE TITLE
Can there be a latest V8, sans Node, version of J2V8?

### ISSUE THREAD

**Issue by JessHolle** [eclipsesource/J2V8#436] opened 2018-11-20 19:44 UTC
For those who only want to embed a high-performance JS runtime, i.e. V8, is there any real need for node?

I ask primarily because there seem to be significant difficulties in building the latest Node for Android, whereas doing so for V8 seems much more feasible (and if nothing else Google is clearly doing it within Chrome).

While I understand that there are those who want all of Node, a "V8 only" option for Android that actually provides the latest V8 (and 32 and 64-bit binaries thereof) is much more important to some of us.

**Comment by irbull** [comment] 2019-01-11 04:40
The reason we moved to node a few years ago was that, at the time, it was easier to build node than to build V8. I think that has changed and I'd be happy to just use V8 as the source instead of Node (we really just build node, pull out the V8 binaries and throw the rest away). I'll leave this open so we can re-evaluate the V8 build.

**Comment by irbull** [comment] 2019-01-11 04:45
Actually, closing as a duplicate of #390. Some good information in that discussion. Thanks!

**Closed by irbull** 2019-01-11 04:45 UTC
