### ISSUE TITLE
couldn't find "libj2v8_android_armv7l.so"

### ISSUE THREAD

**Issue by Brian-McBride** [eclipsesource/J2V8#70] opened 2015-06-12 18:14 UTC
I wanted to check out the performance of your lib in a native Android app. 

I've used both:
compile 'com.eclipsesource.j2v8:j2v8_android_armv7l:2.2.1'
and placing the .jar directly into my libs folder in Android studio.

In each case, I am getting this error:

~~~
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.appname/com.app.appname.MainActivity}: java.lang.IllegalStateException: J2V8 native library not loaded.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2712)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2777)
            at android.app.ActivityThread.access$900(ActivityThread.java:179)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5972)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
     Caused by: java.lang.IllegalStateException: J2V8 native library not loaded.
            at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:86)
            at com.eclipsesource.v8.V8.createV8Runtime(V8.java:74)
            at com.eclipsesource.v8.V8.createV8Runtime(V8.java:63)
            at com.app.appname.MainActivity.onCreate(MainActivity.java:39)
            at android.app.Activity.performCreate(Activity.java:6289)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2777)
            at android.app.ActivityThread.access$900(ActivityThread.java:179)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5972)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
     Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:
    dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app.appname-2/base.apk"],nativeLibraryDirectories=[/data/app/com.app.appname-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libj2v8_android_armv7l.so"
            at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:71)
            at com.eclipsesource.v8.V8.load(V8.java:49)
            at com.eclipsesource.v8.V8.createV8Runtime(V8.java:72)
            ... 15 more
~~~

**Comment by irbull** [comment] 2015-06-12 18:29
On android you need to specify where to unpack the native libraries. We do something like this:
V8.createV8Runtime( activity.getApplicationInfo().dataDir );

**Comment by Anatidae-Project** [comment] 2015-06-12 18:41
Oh, so it will drop the native libs there on runtime? Or is that the directory that the native runtimes need to be living already?

**Comment by Anatidae-Project** [comment] 2015-06-12 19:17
Oh, I should mention that I'm using Android Studio.  It seems as though this is the key:
```
nativeLibraryDirectories=[/data/app/com.globesherpa.ironworks-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libj2v8_android_armv7l.so"
```
I've tried creating my own jniLibs directory with the armeabi, armeabi-v7a, and x86 directories, placing the appropriate .so files in each. No go.

**Comment by irbull** [comment] 2015-06-12 19:24
It will unpack them there. They are in the jar. If you don't specify it
will use ~/.j2v8 but this doesn't work on Android.

**Comment by Anatidae-Project** [comment] 2015-06-12 20:16
Well, this is interesting. I created a jniLibs folder and put the libj2v8_android_armv7l.so in the armeabi-v7a directory. That got passed the error.

However, your example here fails:
```
        String dataDir = this.getApplicationInfo().dataDir;

        V8 runtime = V8.createV8Runtime( dataDir );

        int result = runtime.executeIntScript(""
                + "var hello = 'hello, ';\n"
                + "var world = 'world!';\n"
                + "hello.concat(world).length();\n");
        System.out.println(result);
        runtime.release();
```

Throwing this:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.appname/com.app.appname.MainActivity}: undefined:3: TypeError: number is not a function
    hello.concat(world).length();
    ^
    TypeError: number is not a function
            at <anonymous>:3:21
```

looks like valid JS to me.  It's closer though. I think for Android Studio you'll have to bundle the .jar a little differently so that the .so ends up in the correct directory. That's my guess.

**Comment by irbull** [comment] 2015-06-12 20:38
Sorry, I was trying to answer you from my phone without looking at the code. Ok, two things.

1. Loading to a different location than the default requires the other constructor. 
        V8 runtime = V8.createV8Runtime("", "/tmp");
The one use used sets an alias for the global namespace, that's completely different.

2. The JS you have is not actually valid. length() is not a method, but rather a property:

This works fine:
```
        V8 runtime = V8.createV8Runtime("", "/tmp");
        int result = runtime.executeIntegerScript(""
                + "var hello = 'hello, ';\n"
                + "var world = 'world!';\n"
                + "hello.concat(world).length;");
        System.out.println(result);
        runtime.release();
```

**Comment by vacxe** [comment] 2015-12-07 11:58
I have the same error

  `Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
                                                                               	dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.nitrobubbles.javascriptest-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libj2v8_android_armv7l.so"
`

**Comment by irbull** [comment] 2015-12-07 21:00
Can you try with Version 3.1.0 (just pushed it to maven central 1 hour ago). This packages the androd libs an aar, which should make loading native bits much easier.

```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>3.1.0</version>
  <type>aar</type>
</dependency>
```

**Comment by irbull** [comment] 2015-12-10 01:11
Closing. Please re-open if this problem persists.

**Closed by irbull** 2015-12-10 01:11 UTC
