### ISSUE TITLE
JNI crash converting string which contains emoji

### ISSUE THREAD

**Issue by gborland** [eclipsesource/J2V8#142] opened 2016-04-04 14:35 UTC
When J2V8 calls NewStringUTF with a string which contains emoji, very bad things happen on some
versions of Android:
- On KitKat 4.4 And Lollipop 5.1.1, the converted string contains garbage characters rather than the original emoji.
- On Lollipop 5.0.2, it crashes. This is not a normal exception which can be caught in Java; it **actually kills the VM**. (See error log below.)
- On Marshmallow it appears to work fine.

The underlying cause appears to be an [Android JNI bug](https://code.google.com/p/android/issues/detail?id=81341), but a workaround in J2V8 would help greatly.

```
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]     string: 'Graham emoji test  🕵'
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]     in call to NewStringUTF
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]     from java.lang.String com.eclipsesource.v8.V8._arrayGetString(long, long, int)
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65] "Shared Library JS thread" prio=5 tid=17 Runnable
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x13089470 self=0xa2f40000
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   | sysTid=3257 nice=0 cgrp=apps sched=0/0 handle=0xa2f7b800
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=24 stm=31 core=0 HZ=100
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   | stack=0xa24f4000-0xa24f6000 stackSize=1036KB
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   native: #00 pc 00005ac3  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+83)
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   native: #01 pc 00002e91  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+33)
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   native: #02 pc 003c3f3a  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+138)
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   native: #03 pc 0038e88c  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+284)
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   native: #04 pc 0010131b  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1019)
04-04 14:52:27.563 A: art/runtime/check_jni.cc:65]   native: #05 pc 00101ecc  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+108)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   native: #06 pc 00106b36  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.130)+3046)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   native: #07 pc 0010cd4d  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+93)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   native: #08 pc 001bdadf  /data/app/com.youneedabudget.evergreen.app.develop-1/lib/x86/libj2v8.so (Java_com_eclipsesource_v8_V8__1arrayGetString+367)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   native: #09 pc 00005d1b  /data/data/com.youneedabudget.evergreen.app.develop/cache/slice-com.eclipsesource.j2v8-j2v8-3.1.6_5c07a76fdc937cef5d78831825d3511e148909b6-classes.dex (Java_com_eclipsesource_v8_V8__1arrayGetString__JJI+163)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8._arrayGetString(Native method)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8.arrayGetString(V8.java:1071)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8Array.getString(V8Array.java:173)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8Array.get(V8Array.java:355)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at ynab.sharedlibrary.v8.javascript.V8Transaction.getV8ArrayAsStrings(V8Transaction.java:46)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at ynab.sharedlibrary.v8.javascript.V8Transaction.access$100(V8Transaction.java:23)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at ynab.sharedlibrary.v8.javascript.V8Transaction$1.invoke(V8Transaction.java:62)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8.callVoidJavaMethod(V8.java:778)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8._executeFunction(Native method)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8.executeFunction(V8.java:995)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at com.eclipsesource.v8.V8Function.call(V8Function.java:55)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at ynab.sharedlibrary.v8.javascript.V8Database$1$1.run(V8Database.java:57)
04-04 14:52:27.564 A: art/runtime/check_jni.cc:65]   at android.os.Handler.handleCallback(Handler.java:739)
04-04 14:52:27.565 A: art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:95)
04-04 14:52:27.565 A: art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:135)
04-04 14:52:27.565 A: art/runtime/check_jni.cc:65]   at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by gborland** [comment] 2016-04-04 14:36
Tested with both 3.1.6 and 4.0.0-SNAPSHOT.

**Comment by gborland** [comment] 2016-04-04 14:47
There's a suggested workaround here:
https://github.com/tnt-medallia/android-database-sqlcipher/commit/2c46889df16a2b7478076f8719dfe6929fdfa9b6

**Comment by gosia-eclipsesource** [comment] 2016-04-04 20:14
Thanks for finding a solution. We'll see if we can implement the workaround in J2V8.

**Comment by tabrisjs** [comment] 2016-05-16 21:36
I'm going to close this as a duplicate of #139. I have a PoC working on my machine.

**Comment by irbull** [comment] 2016-05-16 21:38
Sorry, posted with my test account. Closing now.

**Closed by irbull** 2016-05-16 21:38 UTC
